# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

cities:
    slug: cities
    singular_slug: city
    behaves_like: categories
    options:
      novosibirsk: 'Новосибирск'
      biysk: 'Бийск'
      barnaul: 'Барнаул'
      tomsk: 'Томск'
      omsk: 'Омск'
      kemerovo: 'Кемерово'
      novokuznetsk: 'Новокузнецк'
      krasnoyarsk: 'Красноярск'

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true

orders:
    slug: orders
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ news, events, movies, music, books, life, love, fun ]
