# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

cities:
    slug: cities
    singular_slug: city
    behaves_like: categories
    options:
      novosibirsk: 'Новосибирск'
      biysk: 'Бийск'
      barnaul: 'Барнаул'
      tomsk: 'Томск'
      omsk: 'Омск'
      kemerovo: 'Кемерово'
      novokuznetsk: 'Новокузнецк'
      krasnoyarsk: 'Красноярск'
      mountain_altai: 'Горный Алтай'
      belokurikha: 'Белокуриха'
      moscow: Москва
      saint-petersburg: Санкт-Петербург
      yekaterinburg: Екатеринбург
      kazan: Казань
      nizhny_novgorod: 'Нижний Новгород'
      chelyabinsk: Челябинск
      samara: Самара
      rostov-on-don: Ростов-на-Дону
      ufa: Уфа
      voronezh: Воронеж
      perm: Пермь
      volgograd: Волгоград
      krasnodar: Краснодар
      saratov: Саратов
      tyumen: Тюмень
      tolyatti: Тольятти
      izhevsk: Ижевск
      ulyanovsk: Ульяновск
      irkutsk: Иркутск
      khabarovsk: Хабаровск
      yaroslavl: Ярославль
      vladivostok: Владивосток
      orenburg: Оренбург
      ryazan: Рязань
      naberezhnye_chelny: 'Набережные Челны'
      astrakhan: Астрахань
      penza: Пенза
      kirov: Киров
      lipetsk: Липецк
      cheboksary: Чебоксары
      kaliningrad: Калининград
      tula: Тула
      kursk: Курск
      stavropol: Ставрополь
      ulan-ude: Улан-Удэ
      tver: Тверь
      magnitogorsk: Магнитогорск
      ivanovo: Иваново
      bryansk: Брянск
      belgorod: Белгород
      surgut: Сургут
      vladimir: Владимир
      chita: Чита
      nizhny_tagil: 'Нижний Тагил'
      arkhangelsk: Архангельск
      kaluga: Калуга
      smolensk: Смоленск
      cherepovets: Череповец
      saransk: Саранск
      volzhsky: Волжский
      kurgan: Курган
      vologda: Вологда
      orel: Орёл
      tambov: Тамбов
      murmansk: Мурманск
      petrozavodsk: Петрозаводск
      kostroma: Кострома
      crimea: Крым
      kerch: Керчь
      feodosia: Феодосия
      sudak: Судак
      alushta: Алушта
      yalta: Ялта
      sevastopol: Севастополь
      saki: Саки
      evpatoria: Евпатория
      sochi: Сочи
      tuapse: Туапсе
      gelendzhik: Геленджик
      novorossiysk: Новороссийск
      anapa: Анапа
      simferopol: Симферополь

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true

orders:
    slug: orders
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ news, events, movies, music, books, life, love, fun ]
